version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rocketseat-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - primeira-network
  api-rocket:
    container_name: api-rocket
    build:
      context: .
    ports:
      - '3001:3000'
    depends_on:
      - mysql
    networks:
      - primeira-network

networks:
  primeira-network:
    name: primeira-network
    external: true
    driver: bridge

volumes:
  db:
#comandos:
# docker-compose up -d
# docker-compose down
# docker-compose --build -d
