name: CI

on:
  push:
    branches:
      - main

jobs: 
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup node
        uses: actions/setup-node@v3.9.1
        with:
            node-version: 20
            cache: 'npm'
      - run: npm install
      - run: npm run test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }} .
